# 1 Array

In [33]:
import numpy as np

print(np.__version__)

1.25.1


In [34]:
my_list=[2,4,6] ; print(my_list) ; print(type(my_list))
my_tuple=(1,3,5) ; print(my_tuple) ; print(type(my_tuple))

[2, 4, 6]
<class 'list'>
(1, 3, 5)
<class 'tuple'>


In [35]:
my_list=[2,4.0,'hello'] ; print(my_list) ; print(type(my_list))
my_tuple=(1.0,3,'there') ; print(my_tuple) ; print(type(my_tuple))

[2, 4.0, 'hello']
<class 'list'>
(1.0, 3, 'there')
<class 'tuple'>


In [36]:
import numpy as np
a=np.array([2,4,6])
print(a) ; print(type(a))
b=np.array((1,4,6))
print(b) ; print(type(b))

[2 4 6]
<class 'numpy.ndarray'>
[1 4 6]
<class 'numpy.ndarray'>


In [37]:
import numpy as np
a=np.array([2,4.0,6])
print(a) ; print(type(a))
b=np.array(('hello',4,6))
print(b) ; print(type(b))

c=np.array((2,3.9,4))
print(c) ; print(type(c))
d=np.array(('hello',3.9,4))
print(d) ; print(type(d))

[2. 4. 6.]
<class 'numpy.ndarray'>
['hello' '4' '6']
<class 'numpy.ndarray'>
[2.  3.9 4. ]
<class 'numpy.ndarray'>
['hello' '3.9' '4']
<class 'numpy.ndarray'>


## <span style="color: yellow;"> 1-D array   [1,2]</span>

Dimesions are called axis. 

1-D array has 1 dimesion / axis (0 axis only)

In [38]:
import numpy as np
a=np.array([1,2]) # 1-D
print(a)
np.sum(a,axis=0)
# np.sum(a,axis=-1)

[1 2]


3

## <span style="color: yellow;"> 2-D array</span>
Say you have a set of 5 numbers, if sum up those 5 numbers, the result will be a single number.  
Summation effectively arggregates your data. It collapses a large number of values into a single value.  
The axis that you specify is the axis that gets collapsed.  
Aggregation as reducing the dimesionality of the array by 1

In [39]:
import numpy as np
b=np.array([[1,2],[3,4]]) # 2-D array
print(b); print(type(b))
# axis 0 is row, axis 1 is column
x=np.sum(b,axis=0) ; print(x) # [4,6]
y=np.sum(b,axis=1) ; print(y) # [3,7]


[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
[4 6]
[3 7]


In [40]:
import numpy
b = numpy.array([[1,2],[3,4]]) # 2-D
# the added dimesion is the highest, so that will have index 0, and theprevious will
# to eliminate the 0th dimesion and collapse the array along its vertical axis
print(type(b))
ksum0=numpy.sum(b, axis=0) #AXIS 0 IS ROW
print('axis0 = ',ksum0)
#  or eliminate the 1st dimesion and collapse the array along its horizontal axis.
ksum1=numpy.sum(b, axis=1) #axis 1 is column
print('axis1 = ',ksum1)

<class 'numpy.ndarray'>
axis0 =  [4 6]
axis1 =  [3 7]


## <span style="color: yellow;"> 3-D array</span>
Each added dimesion, the new dimesion gets index 0
and all other index are increased by one

In [41]:
import numpy as np
# create a 3-D array of shape(2,2,2)
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
x=np.sum(c,axis=0) ; print('sim of axis 0:',x)
y=np.sum(c,axis=1) ; print('sim of axis 1:',y)
z=np.sum(c,axis=2) ; print('sim of axis 2:',z)
# reduced array of shape(2,2,2) into an array of shape(2,2,1)
z=numpy.sum(c, axis=2)
print('axis2 = ',z)

# 3-D, axis0 layer; axis1 vertical, axis2 horizontal


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
sim of axis 0: [[ 6  8]
 [10 12]]
sim of axis 1: [[ 4  6]
 [12 14]]
sim of axis 2: [[ 3  7]
 [11 15]]
axis2 =  [[ 3  7]
 [11 15]]


In [42]:
# d=np.array([[[1,2],[3,4],[5,6],[7,8]]])
# print(d)
# e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# print(e)

In [43]:
# Array Dimesion
import numpy as np
arr0=np.array(100) # 0-D array
arr1=np.array([1,2,3,4,5]) # 1-D array
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) # 3-D array
print('number of dimesion')
print(arr3.ndim) # return an integer that tells the no. of dimesion

number of dimesion
3


In [44]:
# Create multi dimesional array
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)# create 5 dimesion array
print(arr)
print('no. of dimesion:',arr.ndim)

[[[[[1 2 3 4]]]]]
no. of dimesion: 5


In [45]:
# Array Index
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])
print(arr[2]+arr[3])


2
7


In [46]:
# 2-D Index
import numpy as np
a=np.array([[93,95],
           [84,100],
           [99,97]])
print(a); print(a.shape)
print(a[1,0]) # row1 column0 or axis 0=1 axis 1=0
print(a[-2,0]) # row -2 column 0
print(a[0])   






# axis 0 = row , axis 1 = column

[[ 93  95]
 [ 84 100]
 [ 99  97]]
(3, 2)
84
84
[93 95]


In [47]:
# 2-D index
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2th element on 2nd row:')
print(arr[0,1])
print('5th element on 2nd row:')
print(arr[1,4])

2th element on 2nd row:
2
5th element on 2nd row:
10


In [48]:
# 3D Index
import numpy as np
array=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
# sheet 0 (ie [0,1],[2,3]), row1 (ie [2,3]), column 0 (ie 2)
print(array[0,1,0])
# retrieving 2D array from a 3-D array
print(array[1])



2
[[4 5]
 [6 7]]


In [49]:
# 3-D index
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
# the first number represents the first dimesion
# which contains two arrays [[1,2,3],[4,5,6]] and [[7,8,9],[10,11,12]]
# for '0' in arr [0,1,2], select the first array (ie [[1,2,3],[4,5,6]])
# ....

6


In [50]:
# negative index
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])


10


### Array slicing

In [51]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a',arr[0,:]) # display the 0 row
print('b',arr[:,0]) # display the 0 column
# retrieve 0th row and 0 column
print('c',arr[0:1,0:1]) # retrieve 0th row and 0column
print('d',arr[1:2,1:2])
print('e',arr[1:3,1:]) # 1 to 3 row (3 not inclded),1 to the end column

# print(arr[0,0])
# print(arr[:,:])

a [1 2 3]
b [1 4 7]
c [[1]]
d [[5]]
e [[5 6]
 [8 9]]


In [52]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print('a ',arr[1:5])#[row,start:end:step]
print('b ',arr[1:])#slice element from inde 1 to the end
print('c ',arr[:5])#slice element from the beginning to 5(not included)
print('d ',arr[:6:2])#return every other element
print('e ',arr[::2])
print('f ',arr[1:5:2])#return every other element from index 1 to index 5
print('g ',arr[-3:1])#slice from index 3 from the end to index 1 from the end
print('h ',arr[-1])
print('i ',arr[0])

a  [2 3 4 5]
b  [2 3 4 5 6 7]
c  [1 2 3 4 5]
d  [1 3 5]
e  [1 3 5 7]
f  [2 4]
g  []
h  7
i  1


### Copy and View

.copy .view .base

In [53]:
# Copy .copy
# copies owns the data, and Views does not own the data
import numpy as np

arr = np.array([1,2,3,4,5])
x=arr.copy() # no affected by the changes
arr[0] = 42
print(arr)
print('copy',x)


[42  2  3  4  5]
copy [1 2 3 4 5]


In [54]:
# .view
import numpy as np

arr = np.array([1,2,3,4,5])
x=arr.view() # no affected by the changes
arr[0] = 42
print(arr)
print('view',x)

y=x.base
print('base',y)


[42  2  3  4  5]
view [42  2  3  4  5]
base [42  2  3  4  5]


In [55]:
# .base
# .base return none if the array owns the data
# .copy owns the data
# .view not own the data
import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print('copy base',x.base)
print('view base',y.base)

copy base None
view base [1 2 3 4 5]


### Numpy Boolean Array

In [56]:
import numpy as np
a = np.array([True,True,True])
neg_a=np.logical_not(a)
print(neg_a)

[False False False]


In [57]:
import numpy as np
a=np.array([False,True,False,True])
b=np.array([False,False,True,True])
and_ab=np.logical_and(a,b)
or_ab=np.logical_or(a,b)
xor_ab=np.logical_xor(a,b)
print('a and b',and_ab)
print('a or b',or_ab)
print('a xor b',xor_ab)

a and b [False False False  True]
a or b [False  True  True  True]
a xor b [False  True  True False]


### Numpy Outer Product
An outer product is a procedure in linear algebra that combines two vectors

x:[3,6,8]

y:[4,7,13]

Outer function used in x and y are [3][4,7,13]
Outer product of two vectors are:

[12,21,39]

[24,42,78]

[32,56,104]

In [58]:
import numpy as np
a = np.array([3,5,8])
b=np.array([4,7,13])
np.multiply.outer(a,b)




array([[ 12,  21,  39],
       [ 20,  35,  65],
       [ 32,  56, 104]])

In [59]:
print(np.outer(a,b))

[[ 12  21  39]
 [ 20  35  65]
 [ 32  56 104]]


### Revision

In [60]:
a=[2,4.0,'hello',8] # list
print(a); print('type=',type(a))
b=3,5,7 # tuple
print(b); print('type=',type(b))

[2, 4.0, 'hello', 8]
type= <class 'list'>
(3, 5, 7)
type= <class 'tuple'>


In [61]:
import numpy
a=[2,4,6,8]
b=numpy.array(a) # from list to Multi dimension (nd) to numpy array
print(b) # 1 D array
print(type(b))
print('dimension',b.ndim)

# .To_list from numpy array to list variable

[2 4 6 8]
<class 'numpy.ndarray'>
dimension 1


In [62]:
# a=numpy.zeros(6)
# print(a)
b=numpy.ones(6)
print(b) # 1 D array
c=b.reshape(2,3) # reshape the array to 2D with 2 rows and 3 columns
print(c)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [65]:
# 2D array # [2,4,6,8]
a=numpy.array([[2,4],[6,8]]) # [x,y] where x=[2,4] and y=[6,8]
print(a)
print('dimension ',a.ndim)
print('shape ',a.shape) # 2D array shape=(number of row, number of column)

[[2 4]
 [6 8]]
dimension  2
shape  (2, 2)


In [ ]:
import numpy
a=numpy.array([[[2,4],[6,8]],[[5,6],[7,8]]]) #3D
# [[2,4],[6,8]] is one layer and [[5,6],[7,8]] another layer
print(a)
print('dimension ',a.ndim)
print('shape ',a.shape) # 3D array shape=(layer number,number of row, number of column)
print('type ',type(a))
print('element type ',a.dtype)

[[[2 4]
  [6 8]]

 [[5 6]
  [7 8]]]
dimension  3
shape  (2, 2, 2)
type  <class 'numpy.ndarray'>
element type  int32


In [ ]:
import numpy
a=numpy.array([[[2,4],[6,8]],[[5,6],[7,'hello']]]) #3D
# [[2,4],[6,8]] is one layer and [[5,6],[7,8]] another layer
print(a)
print('dimension ',a.ndim)
print('shape ',a.shape) # 3D array shape=(layer number,number of row, number of column)
print('type ',type(a))
print('element type ',a.dtype)

[[['2' '4']
  ['6' '8']]

 [['5' '6']
  ['7' 'hello']]]
dimension  3
shape  (2, 2, 2)
type  <class 'numpy.ndarray'>
element type  <U11
