# 3 Shape

### Numpy Array Shape

In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]]) # 2D
print(a) ; print(a.ndim)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [2]:
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D 2 payer
print(a) ; print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [3]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,120]],[[1,2,3],[4,5,6]]]) # 3D 3 payer
print(a) ; print(a.ndim)
print(a.shape)

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11 120]]

 [[  1   2   3]
  [  4   5   6]]]
3
(3, 2, 3)


In [6]:
# create a 5 dimesions array
import numpy as np
a=np.array([1,2,3,4],ndmin=5)
print(a)
print(a.shape)
print('x',a[0,0,0,0,2]) # 5 D array with 1 to 4 dimesions have 1 element
# and the fifth has 4
print('y',a[0,0,0,0,:])
print('z',a[0,0,0,:,1:3])

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
x 3
y [1 2 3 4]
z [[2 3]]


In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.shape)
b=a.reshape(4,3) # 2D array 4 row 3 column from 1D array with 12 rows
print(b)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12]) # 1D
print('shape ',a.shape); print('dimension ',a.ndim)
b=a.reshape(2,3,2) # 3D array 3 row 2 column from 1D array with 12 rows
print(b) ; print('dimension',b.ndim)

shape  (12,)
dimension  1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
dimension 3


In [9]:
# .base
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12]) # 1D
b=a.reshape(2,3,2).base # 3D array 3 row 2 column from 1D array with 12 rows
print(b) ; print('dimension',b.ndim) # check if the return array is a copy or view

[ 1  2  3  4  5  6  7  8  9 10 11 12]
dimension 1


In [10]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8]) # 1D
b=a.reshape(2,2,-1) #
print(b) ; print('dimension',b.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension 3


In [11]:
# reshape(-1)
import numpy as np
a=np.array([[1,2,3],[4,5,6]]) # 2D array
b=a.reshape(-1) # reshape(-1) flattening array to convert multi dimesional array 
# into a 1D array
print(b)

[1 2 3 4 5 6]


In [12]:
# .Transpose
import numpy as np
a=np.array([[1,2,3],[4,5,6]]) # 2D array
print(a); print(a.ndim)
b=a.T
print(b); print(b.ndim)

[[1 2 3]
 [4 5 6]]
2
[[1 4]
 [2 5]
 [3 6]]
2
