# JoinSplit

### Joining Numpy Arrays
Put contents of two or more arrays in a single array

.concatenate()
the function joins elements of two arrays along an existing axis

In [2]:
# . concatenate()
import numpy as np
arr1=np.array([1,2,3]) #1D array
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2)) # default axis=0
print(arr)

[1 2 3 4 5 6]


In [3]:
# .stack
import numpy as np
arr1=np.array([1,2,3]) #1D array
arr2=np.array([4,5,6])
arr_axis1=np.stack((arr1,arr2),axis=1) # 2D array
print(arr_axis1)
arr_axis0=np.stack((arr1,arr2),axis=0) # 2D array
print(arr_axis0)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [4]:
# 2D
# . concatenate()
import numpy as np
arr1=np.array([[1,2],[3,4]]) #2D array
arr2=np.array([[5,6],[7,8]])
arr_axis1=np.concatenate((arr1,arr2),axis=1) #  
arr_axis0=np.concatenate((arr1,arr2)) # default axis=0
print(arr_axis1);print(arr_axis0)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
#.append
a=np.zeros([1,2])# generate an array with zero number with shape row =1 column 2
print(a), print(a.ndim)
b=np.append(a,[[2,3]],axis=0) # numpy.append(input, value, axis)
print(b), print(b.ndim)

[[0. 0.]]
2
[[0. 0.]
 [2. 3.]]
2


(None, None)

In [11]:
# insert
a=np.zeros([1,2])# generate a 2Darray zero with shape row =1 column 2
# print(a), print(a.ndim)
b=np.append(a,[[2,3]],axis=0) # numpy.append(input, value, axis)
print(b) #;print(b.ndim)
c=np.insert(b,[2],[4.5],axis=0) # numpy.insert(input,location, value, axis)
print(c);# print(c.ndim)

[[0. 0.]
 [2. 3.]]
