### Array Search
Search an array for a certain value and return the index that get a match

In [4]:
# .where
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4) # return index when condition (ie arr is equal to 4) matched
print(x) # return array[index]
y=np.where(arr%2==0); print(y) # % remainder
z=np.where(arr%2==1); print(z)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


In [1]:
# Sort

import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [3]:
import numpy as np
arr=np.array(['cherry','d','apple','egg']) # 1D
print(np.sort(arr))

['apple' 'c' 'd' 'egg']


In [6]:
# Sort 2D

import numpy as np
arr=np.array([[6,2,1],[5,8,1]]) # 2D
a=np.sort(arr);print('a ',a)
b=np.sort(arr, axis=0);print('b ',b)
c=np.sort(arr, axis=1);print('c ',c)
d=np.sort(arr, axis=None);print('d ',d)

a  [[1 2 6]
 [1 5 8]]
b  [[5 2 1]
 [6 8 1]]
c  [[1 2 6]
 [1 5 8]]
d  [1 1 2 5 6 8]


### Array Filter
Getting some elements but of an existing array and creating a new array out of them is called filter

In [8]:
import numpy as np

arr=np.array([41,42,43,44])
x=[True, False, True, False]
y=arr[x]
print(y)

[41 43]


In [11]:
import numpy as np
arr=np.array([41,42,43,44])
# create an empty list
filter_arr=[]
# go though each element in arr
for element in arr:
    # if the element in higher than 42, set the value to True, other False
    if element >42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr] #filtering action
print(filter_arr)
print(newarr)
    

[False, False, True, True]
[43 44]


In [12]:
import numpy as np
arr=np.array([41,42,43,44])
b=arr > 42 # create a filter array that will return values > 42
newarr=arr[b]
print(b)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
import numpy as np
arr=np.array([41,42,43,44])
# create an empty list
b=[]
# go though each element in arr
for element in arr:
    # if the element in higher than 42, set the value to True, other False
    if element >42:
        b.append(True)
    else:
        b.append(False)
newarr=arr[b] #filtering action ie [False, False, True, True]
print(b)
print(newarr)