### Create Universial function

In [4]:
# .frompyfunc(in function,no.of in argument,no.out array)
import numpy as np
def a(x,y):
    b=x+y
    return(b)
ufun=np.frompyfunc(a,2,1) # a = function 2 = number of input 1 = output
AA=ufun([1,2,3,4],[5,6,7,8]) # two values add up
print(AA)
print(type(ufun))
print(type(AA))
print(type(a))

[6 8 10 12]
<class 'numpy.ufunc'>
<class 'numpy.ndarray'>
<class 'function'>


In [5]:
import numpy as np
def a(x,y):
    b=x+y
    return(b)
BB=a([1,2,3,4],[5,6,7,8]) # add two lists give a joined list
print(BB)

[1, 2, 3, 4, 5, 6, 7, 8]


In [6]:
# np.add is a u function
import numpy as np
a=np.add([1,2,3,4],[5,6,7,8])
print(a)
print(type(np.add))

[ 6  8 10 12]
<class 'numpy.ufunc'>


In [7]:
# np.add is a u function
# import numpy as np
# x=np.array([1,2,3,4])
# y=np.array([10,20])
# np.add.at(x,[0,3],y) # x+y under condition [0,3], result in x
# print(x)
import numpy as np
x=np.array([1,2,3,4])
y=np.array([10,20,30,40])
AA=np.add(x,y)
print(AA)

[11 22 33 44]


In [8]:

# .accumulate()
import numpy as np
a=np.array([2,4,6])
b=np.add.accumulate(a) # accumulation
print(b)# 2, 2+4, 2+4+6

c=np.multiply.accumulate(b)
print(c)

d=np.arange(100)
d=np.delete(d,np.s_[0])
print(d)
e=np.multiply.accumulate(d)
print(e)

[ 2  6 12]
[  2  12 144]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736 -1195114496  -522715136   862453760  -775946240
  2076180480 -1853882368  1484783616 -1375731712 -1241513984  1409286144
   738197504 -2147483648 -2147483648           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0   

In [9]:
# .add() add up two arguments
# .add(x,y) add is done between two arguments
# .sum([x,y]) sum of all elements

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.sum([a,b])
print('.sum()',x)
y=np.add(a,b)
print('.add()',y)

.sum() 21
.add() [5 7 9]


In [10]:
# np.subtract
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.subtract(b,a)
print(x)

[3 3 3]


In [24]:
# np.multiply
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.multiply(b,a)
print(x)

c=b*a[1]
print(c)

[ 4 10 18]
[ 8 10 12]


In [12]:
# np.prod([x,y])
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.prod([b,a],axis=0)
y=np.prod([b,a],axis=1)
z=np.prod([a,b],axis=1)
print('axis0',x)
print('axis1',y)
print('axis1',z)

axis0 [ 4 10 18]
axis1 [120   6]
axis1 [  6 120]


In [13]:
# np.divide(x,y)
a=np.array([8,21,18])
b=np.array([4,5,6])
x=np.divide(a,b)
y=np.divide(b,a)
print(x); print(y)


[2.  4.2 3. ]
[0.5        0.23809524 0.33333333]


In [14]:
# np.power(x,y)
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.power(b,a)
y=np.power(a,b)
print(x); print(y)

[  4  25 216]
[  1  32 729]


In [15]:
# np.mod(x,y)
# np.remainder(x,y)
a=np.array([10,20,30])
b=np.array([3,7,9])
x=np.mod(a,b) # [10-3x3=1,]
y=np.remainder(a,b)
print('mod',x)
print('remainder',y)

mod [1 6 3]
remainder [1 6 3]


In [16]:
# np.absolute
import numpy as np
a=np.array([-1,-2,-3,4,-5,6,7,-8])
x=np.absolute(a)
print(x)

[1 2 3 4 5 6 7 8]
