### LCM Lowest Common Multiple

In [2]:
import numpy as np

a=4
b=6
x=np.lcm(a,b)
print(x) # 4x3=12 ; 6x2=12

12


In [6]:
# HCF
a=198
b=360
x=np.gcd(a,b) # HCF
print('HCF ',x)
y=a*b/x # by calculation
print(y) # LCM
z=np.lcm(a,b) # by numpy built-in function
print(z) # LCM

HCF  18
3960.0
3960


### Reduce() method 
returns a single ?

In [9]:
import numpy as np
a=np.array([3,6,9])
x=np.lcm.reduce(a) # reduce the array by one dimension
print(x)

18


In [13]:
import numpy as np
a=np.array([3,6,9])
b=np.array([13,61,9])
c=np.add(a,b) ; print('add',c) # 1D array ie [x,y,z]
d=np.sum(c); print('sum',d)
e=np.add.reduce(c); print('add reduce',e) # reduce 1 dimension to 0 D
# 0D is a point

add [16 67 18]
sum 101
add reduce 101


4 data type in Python

1. List [ ]
2. Dictionary { }
3. Tuple ( )
4. Set ( )

### Numpy Set Operations

In [19]:
# np.unique()
# the method find unique elements from array
import numpy as np
a=np.array([1,1,1,2,2,3,4,5,5,6,7])
b=np.unique(a)
print(b) ; print(type(b))
x=set([1,1,1,2,2,3,4,5,5,6,7]) ; print(type(x))
print(x)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
<class 'set'>
{1, 2, 3, 4, 5, 6, 7}


In [20]:
# np.union(x,y)
import numpy as np
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])
AA=np.union1d(x,y)
print(AA)

[1 2 3 4 5 6]


In [6]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=True)
print(x)

[3 4]


In [7]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([4,2,3,4])
b=np.array([6,4,5,6])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=True)
print(x)

[4 4 6]


In [14]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([0,1,0,1])
b=np.array([1,0,1,0])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=True)
print(x)

[0 0 0 1 1 1]


In [18]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([0,1,0])
b=np.array([1,0])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=True)
print(x)

[0 0 1]


In [19]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([0,1,0,1,0,1])
b=np.array([1,0,1,0,1,0])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=True)
print(x)

[0 0 0 0 0 1 1 1 1 1]


In [24]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([1,1,1,1,4])
b=np.array([0,2,0,2,3,3])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=False)
print(x)

[]


In [25]:
# np.intersect1d()
# find intersection of two arrays and
# return the sorted, unique values that are in both input array

import numpy as np
a=np.array([1,1,1,1,4])
b=np.array([0,2,1,2,3,3])
# assume_unique default False, set True to speed up
x=np.intersect1d(a,b,assume_unique=False)
print(x)

[1]


In [26]:
# np.intersect1d()
# find difference of the set1 from set2
import numpy as np
set1=np.array([1,2,3,4])
set2=np.array([3,4,5,6])
x=np.intersect1d(set1,set2) # view from set2
print(x)

[3 4]


In [28]:
# np.setxor1d()
# values that are nott present in both sets

import numpy as np
set1=np.array([1,2,3,4])
set2=np.array([3,4,5,6])
AA=np.setxor1d(set1,set2)
print(AA)

[1 2 5 6]
