### Cheating Array

In [1]:
import numpy as np


In [5]:
# create 1D array
a=np.array([1,2,3])
#2D array
b=np.array([[1.4,2.0,3.0],[4,5,6]],dtype=float)
# 3D array
c=np.array([[(1.5,2.0,3.0),(4,5,6)],[(3,2,1),(3,4,5)]],dtype=float)
# print(c)
print(c.ndim)
print(c.shape)

3
(2, 2, 3)


### Initial Placeholders

In [15]:
# Create an array of zeros, ones
a=np.zeros((3,4))
b=np.ones((2,3,4),dtype=np.int16)

# Create an array of evenly spaced valued (step value)
c=np.arange(10,25,5)

# Create an array of evenly saced values (number of samples)
d=np.linspace(0,2,9)# (start, end, np of samples)

# Create a constant array
e=np.full((2,2),7)# (shape,filled with a specified value)

# Create a 2x2 identity matrix
f=np.eye(2) # 1 on the main diagonal, and 0 everywhere else

# Create an array with random values
g=np.random.random((2,2))

# Create an empty array
h=np.empty((3,2))
h

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

### Arithmetic Operation

In [17]:
AA=[5,6,7]
BB=[1,2,3]
# Subtraction
i=np.subtract(AA,BB)
# Addition
j=np.add(AA,BB)
# Division
k=np.divide(AA,BB)
# Multiplication
l=np.multiply(AA,BB)

### Sorting Arrays

In [22]:
a=np.array([3,1,8,9,6])
AA=np.array([[1,2,3],[4,5,6]])
# Sort an array
a.sort()
# Sort an array reverse order
m=sorted(a,reverse=True)
AA.sort(axis=0)

### Array Manipiulation

In [31]:
AA=np.array([[1,2,3],[4,5,6]])
BB=np.array([[1,2,3],[4,5,6]])
CC=np.array([1,2,3])
DD=np.array([4,5,6])
EE=np.array([[1,2,3,9],[4,5,6,8],[7,8,9,7],[10,11,12,6]])
# Transposing array
n=AA.T

# Changing array Shape
o=AA.ravel() # flatten the array
p=AA.reshape(3,2)# return an reshaped array and no change of data
AA.resize(2,3)# return none value and changed of original shape
q=np.append(BB,[[2,3,4]],axis=0)# append items to an array
r=np.insert(BB,[1],[10,11,12],axis=0)# insert to row 2
s=np.delete(BB,[1],axis=0)# delete item from an array
print(s)
print('BB',BB)

# Combining arrays
t=np.concatenate((CC,DD))# concatenate two arrays
u=np.vstack((CC,DD))# stack arrays vertically(row-wise)
v=np.hstack((CC,DD))# horizontally

# Splitting array
r=np.vsplit(EE,2)# Split the array verically
s=np.hsplit(EE,2)# horizontally

[[1 2 3]]
BB [[1 2 3]
 [4 5 6]]


[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3,  9],
        [ 6,  8],
        [ 9,  7],
        [12,  6]])]