In [2]:
import numpy as np
# create a 3-D array of shape(2,2,2)
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(c)
x=np.sum(c,axis=0) ; print('sim of axis 0:',x)
y=np.sum(c,axis=1) ; print('sim of axis 1:',y)
z=np.sum(c,axis=2) ; print('sim of axis 2:',z)

from mpl_toolkits.mplot3d import axes3d



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
sim of axis 0: [[15 18]
 [21 24]]
sim of axis 1: [[ 4  6]
 [12 14]
 [20 22]]
sim of axis 2: [[ 3  7]
 [11 15]
 [19 23]]


In [3]:
import numpy as np
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

x=np.sum(c,axis=0) ; print('sim of axis 0:',x)
y=np.sum(c,axis=1) ; print('sim of axis 1:',y)
z=np.sum(c,axis=2) ; print('sim of axis 2:',z)

sim of axis 0: [[ 8 10 12]
 [14 16 18]]
sim of axis 1: [[ 5  7  9]
 [17 19 21]]
sim of axis 2: [[ 6 15]
 [24 33]]


In [4]:
import numpy as np
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

x=np.sum(c,axis=0) ; print('sum of axis 0:',x)
y=np.sum(c,axis=1) ; print('sum of axis 1:',y)
z=np.sum(c,axis=2) ; print('sum of axis 2:',z)


sim of axis 0: [[ 4  6]
 [ 8 10]]
sim of axis 1: [[ 2  4]
 [10 12]]
sim of axis 2: [[ 1  5]
 [ 9 13]]
