Numpy Exercise 1

In [17]:
# 1
import numpy as np
np.__version__ # double __

'1.25.1'

In [18]:
# 2
# create a 10 array of number from 0 to 9
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 3
# create 3x3 numpy
a=np.ones((3,3)) ; print(a)
# create 3x3 nump boolean array of all True
np.ones((3,3),dtype=bool)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
# 4
# Extract items that satisfy a given condition
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]


array([1, 3, 5, 7, 9])

In [21]:
# Replace items that satisify a given condition
arr=np.arange(10) ; print(arr)
arr[arr %2 ==1] = -1
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
# 6
# Replace items
arr=np.arange(10)
arr2=np.where(arr % 2 ==1,-1,arr)
# np.where return the index of element 
# that satify the condition
print('arr',arr);print('arr2',arr2)


arr [0 1 2 3 4 5 6 7 8 9]
arr2 [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [23]:
# 7 
# Reshape
arr=np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# set -1 to determine the number of column automatically
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# 8
# Stack twp arrays vertically
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
x=np.concatenate([a,b],axis=0) ; print('method 1',x) # method 1
y=np.vstack([a,b]) ; print('method 2',y) # method 2

method 1 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
method 2 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
# STack two arrays horizontally
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
x=np.concatenate([a,b],axis=1); print(x) # axis =1 . method 1
y=np.hstack([a,b]); print(y) # method 2

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [27]:
# 10
# Generate
arr=np.array([1,2,3])
np.concatenate([np.repeat(arr,3),np.tile(arr,3)],axis=0) # method 1
y=np.hstack([np.repeat(arr,3),np.tile(arr,3)]); print(y) # method 2

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [28]:
# 11
# Get common item
a=np.array([1,2,3,2,3,4,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [29]:
# 12
# remove from
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [30]:
# 13
# Get the position
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,19,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [44]:
# 14
# Extract all number
a=np.array([2,6,1,9,10,3,27])
a[(a>=5)&(a<=10)] # method 1
b=[x for x in a if x>=5 if x<=10] ; print(b) # method 2
c=list(filter(lambda x:(x>=5)&(x<=10),a)) ; print(c) # method 3

[6, 9, 10]
[6, 9, 10]


In [45]:
# 15
# Make a python function
a=np.array([6,7,9,8,6,4,5])
b=np.array([6,3,4,8,9,7,1])
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
pair_max=np.vectorize(maxx)
pair_max(a,b)
AA=list(map(lambda x,y:maxx(x,y),a,b)) ; print(AA) # method 2

array([6, 7, 9, 8, 9, 7, 5])

In [47]:
# 16
# Swap
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [ ]:
# 17
arr=np.arange(9).reshape(3,3)
arr

In [49]:
x=arr[0,:] ; print('x ',x)
y=arr[[2,1,0],:]
# 1D indexing [start:end:step]
# 2D indexing [Row start:end:step,Column start:end:step]
# 3D indexing [sheet , Row start:end:step,Column start:end:step]
print('y ')
print(y)

x  [0 1 2]
y 
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [50]:
# 18
# Reverse
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
arr[[3,2,1,0],:]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [52]:
arr[::-1] 
# a[::-1] all items in the array reversed

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [53]:
# 19
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
arr[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])