## Numpy Exercise 3

In [2]:
import numpy as np

In [3]:
# 53
a=np.array([1,2,3])
b=np.power(a,2)
print(b)

[1 4 9]


In [4]:
a=np.array([4,9,16])
b=np.sqrt(a)
print(b)

[2. 3. 4.]


In [5]:
# 54
a=np.array([True,False,True])
b=np.logical_not(a)
print(b)

[False  True False]


In [6]:
a=np.array([False,True,False,True])
b=np.array([False,False,True,True])
and_ab=np.logical_and(a,b)
or_ab=np.logical_or(a,b)
xor_ab=np.logical_xor(a,b)
print(and_ab)
print(or_ab)
print(xor_ab)

[False False False  True]
[False  True  True  True]
[False  True  True False]


In [7]:
# 56
a=np.array([1,2,3,4])
np.negative.at(a,[0,1])
a

array([-1, -2,  3,  4])

In [8]:
# 57
a=np.array([1,2,3,4])
b=np.array([1,2])
np.add.at(a,[0,1],b)
a

array([2, 4, 3, 4])

In [28]:
# 58
a=np.array([1,2,3])
b=np.add.accumulate(a)
c=np.multiply.accumulate(a)
print('b',b)
print('c',c)

b [1 3 6]
c [1 2 6]


In [10]:
# 59
a=np.array([2,3,4])
b=np.multiply.reduce(a)
b

24

In [11]:
c=b=np.add.reduce(a)
c

9

In [12]:
d=np.power.reduce(a)
d

4096

In [16]:
# 60
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.multiply.outer(a,b)
print('x',x)
y=np.multiply(a,b)
print('y',y)

x [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
y [ 4 10 18]


In [20]:
# 61
a=np.array([1,2,3])
b=np.array([0,2,4])
x=np.power(a,b)
print(x)
y=np.float_power(a,b)
print(y)

[ 1  4 81]
[ 1.  4. 81.]


In [25]:
# 62
a=np.array([3,5,7])
b=np.array([2,3,4])
x=np.remainder(a,b)
print(x)
y=a%b
print(y)
z=np.mod(a,b)
print(z)

[1 2 3]
[1 2 3]
[1 2 3]


In [27]:
# 63
a=np.array([7,7,7,11])
b=np.array([2,3,4,5])
x=np.divide(a,b)
print(x)
y=np.floor_divide(a,b)
print(y)

[3.5        2.33333333 1.75       2.2       ]
[3 2 1 2]
