NumPy Exercises 1 - 2

1. Import numpy as np and print the version number.

2. Create a 1D array of numbers from 0 to 9
$> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np 
np.__version__ # Import numpy as np and print the version number.

'1.25.1'

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a 3×3 numpy boolean array of all True’s
array([[ True, True, True],
      [ True, True, True],
      [ True, True, True]], dtype=bool)

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 4. Extract items that satisfy a given condition from 1D array

# Extract all odd numbers from arr

# Given that:
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired output:
# array([1, 3, 5, 7, 9])

In [6]:
# Given input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
# 5. Replace items that satisfy a condition with another value in numpy array
# Replace all odd numbers in arr with -1

# Given Input (in #4):
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired Output:
# array([0, -1, 2, -1 ,4, 6, -1, 8, -1])

In [8]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# 6. Replace items that satisfy a condition without affecting the original array,
# and use np.where()function, and store value in arr2

# Replace all odd number in arr with -1 without changing arr

# Given Input:
# arr = np.arange(10)
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

# Desired Output:
# arr2
# array([0, 01, 2, -1, 6, -1, 8, -1])

In [10]:
arr = np.arange(10)
arr2 = np.where(arr % 2 == 1, -1, arr)
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 7. Reshape an array

# Convert a 1D array to a 2D array with 2 rows

# Given Input:
# np.arange(10)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired Output:
# array([0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9])

In [13]:
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# Setting to -1 automatically decides the number of cols
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
# 8. Stack two arrays vertically

# Stack arrays a and b vertically

# Given Input:
# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)

# Desired Output:
# array([0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9],
#       [1, 1, 1, 1, 1],
#       [1, 1, 1, 1, 1])

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# 9. Stack two arrays horizontally

# Stack the arrays a and b horizontally.

# Given Input:
# a = np.arrange(10).reshape(2,-1)
# b = np.repeat(1,10).reshape(2,-1)

# Desired Output:
# array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [20]:
# Method 2:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [21]:
# 10. Generate custom sequences in numpy without hardcoding

# Create the following pattern without hardcoding.
# Use only numpy fuctions and the below input array arr

# Given Input:
# arr = np.array([1,2,3])

# Desired Output:
# array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
arr = np.array([1,2,3])
np.concatenate([np.repeat(arr, 3), np.tile(arr,3)], axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
# method 2
np.hstack([np.repeat(arr, 3), np.tile(arr, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
# 11. Get the common items between two python numpy arrays

# Get the common items between a and b

# Given Input:
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:
# array([2,4])

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [26]:
# 12. Remove from one array those items that exist in another

# From array a remove all items present in array b

# Given Input:
# a = np.array([1,2,3,4,5])
# b = np.array([5,6,7,8,9])

# Desired Output:
# array([1,2,3,4])

In [27]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [28]:
# 13. Get the positions where elements of two arrays match

# Get the positions where elementsof two arrays match

# # Given Input:
# # a = np.array([1,2,3,2,3,4,3,4,5,6])
# # b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:
# (array([1, 3, 5, 7]),)

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [30]:
# 14. Extract all numbers between a given range from a numpy array

# Get all items between 5 ande 10 from a.

# Given Input:
# a = np.array([2, 6, 1, 9, 10, 3, 27])

# Desired Output:
# array([6, 9, 10])
# or
# [6, 9, 10]

In [31]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [32]:
# Method 2
# [ expression for item in list if conditional]
[x for x in a if x>=5 if x<=10]

[6, 9, 10]

In [33]:
# Method 3
list(filter(lambda x: (x>=5) & (x<=10),a))

[6, 9, 10]

In [34]:
# 15. Make a python function that handles scalars to work on numpy arrays

# Convert the function maxx that works on two scalars, to work on two arrays.

# Given Input:
# def maxx(x, y):
# #     """Get the maximum of two items"""
# #     if x >= y:
# #         return x
# #     else:
# #         return y
# maxx(1, 5)
# $> 5

# Desired Output:
# a = np.array([5, 6, 7, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# $> array([6, 7, 9, 8, 9, 7, 5])
# or
# [6, 7, 9, 8, 9, 7, 5]

# Hints: No need to write another function. Just vectorize it

In [35]:
a = np.array([5, 6, 7, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Method 1
pair_max = np.vectorize(maxx)
pair_max(a, b)

array([6, 6, 7, 8, 9, 7, 5])

In [36]:
# Method 2
list(map(lambda x, y: maxx(x,y), a, b))

[6, 6, 7, 8, 9, 7, 5]

In [37]:
# 16. Swap two columns in a 2d numpy array

# Swap column 0 and 1 in the array arr.

# Given Input:
# arr = np.arange(9).reshape(3,3)
# arr
# array([[0, 1, 2],
#       [3, 4, 5],
#       [6, 7, 8]])

# Desired Output:
# array([[1, 1, 2],
#       [4, 3, 5],
#       [7, 6, 8]])

In [38]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [40]:
# 17. Swap two rows in a 2d numpy array

# Swap rows 0 and 2 in the array arr:

# Given input:
# arr = np.arange(9).reshape(3,3)
# arr
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

# Desired Output:
# array([[6, 7, 8],
#        [3, 4, 5],
#        [0, 1, 2]])

In [41]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr[[2,1,0], :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [43]:
# 18. Reverse the rows of a 2D array

# Reverse the rows of a 2D array arr.
# Given Input:
# arr = np.arange(12).reshape(4,3)
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8],
#        [9, 10, 11],])

# Desired Output:
# array([[9, 10, 11],
#        [6, 7, 8],
#        [3, 4, 5],
#        [0, 1, 2]])

SyntaxError: invalid decimal literal (2316722998.py, line 1)

In [ ]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [ ]:
# 19. Reverse the column of a 2D array

# Reverse the column of a 2D array arr.
# Given Input:
# arr = np.arange(15).reshape(3,5)
# array([[0, 1, 2, 3, 4],
#        [5, 6, 7, 8, 9],
#        [10, 11, 12, 13, 14]])

# Desired Output:
# array([[4, 3, 2, 1, 0],
#        [9, 8, 7, 6, 5]
#        [14, 13, 12, 11, 10]])


In [ ]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])