## Numpy Exercise 2

In [2]:
# 20
# random.int gives integer
# random.read gives float between 0.0 and 1.0 but not include 1.0
# random.uniform gives float in given range between a and b
import numpy as np
from numpy import random
# generate a 2D array with row 5 and column 3 between 5 to 10
print(np.random.uniform(5,10, size=(5,3))) # uniform distribution

[[5.16819556 7.72313196 6.87711661]
 [5.11903033 5.67826316 6.89668071]
 [9.11060083 7.51748055 7.52817111]
 [7.51152376 5.16176667 5.10643176]
 [5.99574922 7.66394098 6.97549873]]


In [3]:
# 21
a=np.random.random([2,2]) # generate random array
print(a)
b=np.round(a,3) # round to 3 place
print(b)

[[0.75312012 0.5623776 ]
 [0.44672667 0.59801006]]
[[0.753 0.562]
 [0.447 0.598]]


In [37]:
# 22
a=np.random.random([3,3])/1e3
print(a)
np.set_printoptions(suppress=True, precision=6)
# precision: number of digits for floating point output
# suppress: if true, print floating point number
np.set_printoptions(suppress=False)
print(a)

[[6.967056e-04 5.418531e-04 1.512378e-04]
 [8.608117e-04 3.122213e-04 1.789888e-05]
 [7.354705e-04 9.090538e-04 7.312138e-04]]
[[6.967056e-04 5.418531e-04 1.512378e-04]
 [8.608117e-04 3.122213e-04 1.789888e-05]
 [7.354705e-04 9.090538e-04 7.312138e-04]]


In [ ]:
# 23
np.set_printoptions(threshold=6)
a=np.arrange(15)
print(a)