In [2]:
import numpy as np
x=np.arange(0,100)
y=np.delete
np.split(x,[0,2,4])

[array([], dtype=int32),
 array([0, 1]),
 array([2, 3]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
        89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [4]:
import numpy as np
arr = np.array([-1.99,-1.13,0.56,1.28,2.10,2.65])
np.trunc(arr)

array([-1., -1.,  0.,  1.,  2.,  2.])

In [7]:
import numpy as np
from numpy import random
random.rand(4,5)

array([[0.52914742, 0.37861686, 0.58752114, 0.16215559, 0.12852929],
       [0.76866236, 0.9140684 , 0.27859169, 0.12002676, 0.01943465],
       [0.70820249, 0.85436782, 0.99372476, 0.58238827, 0.29952117],
       [0.82418468, 0.00126877, 0.81441856, 0.16038806, 0.94130318]])

In [17]:
import numpy as np
arr = np.array([[1,2,3],
               [4,np.nan,6],
               [7,8,9],
               [np.nan,np.nan,np.nan]])

np.isnan(arr)

np.where(arr = str, 0,arr)


SyntaxError: positional argument follows keyword argument (3029191164.py, line 9)

In [8]:
None,None,None,None,None,None,None,None,None,None,None,None,None

(None, None, None, None, None, None, None, None, None, None, None, None, None)

In [22]:
import numpy as np
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
'0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99'

'0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99'

In [7]:
import numpy as np
np.arange(1,7).reshape(3,2) + np.ones(2)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [10]:
import numpy as np
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])