Question 1
Create a shape (3, 4) Numpy array named arr as follow table, and format dtype as float32
1.2	1.4	1.6	1.8
2.3	2.5	2.7	2.9
3.4	3.6	3.8	4.0

In [2]:
import numpy as np
arr=np.array([1.2,1.4,1.6,1.8,2.3,2.5,2.7,2.9,3.4,3.6,3.8,4.0],dtype='float32')
arr=arr.reshape(3,4)
arr

array([[1.2, 1.4, 1.6, 1.8],
       [2.3, 2.5, 2.7, 2.9],
       [3.4, 3.6, 3.8, 4. ]], dtype=float32)

Question 2
Write code to show:
(a)	arr’s shape, and
(b)	dtype

In [3]:
print("arr’s shape is",arr.shape,",and")
print("arr’s dtype is",arr.dtype)


arr’s shape is (3, 4) ,and
arr’s dtype is float32


Question 3
Write code to calculate the square root of the arr, store the value in arr_sqrt and show the value.

In [4]:
arr_sqrt=np.sqrt(arr)
arr_sqrt

array([[1.0954452, 1.183216 , 1.264911 , 1.3416407],
       [1.5165751, 1.5811388, 1.6431677, 1.7029387],
       [1.8439089, 1.8973665, 1.9493588, 2.       ]], dtype=float32)

Question 4
Create a new Boolean array named arr2, to store the Boolean value of checking arr each value is greater and equal to 2.7. 
 >>> arr2
array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
arr2=arr > 2.7
arr2

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

Question 5
Multiply the arr by 3 then minus 2, store the value in arr_cal. And show the array value.

In [6]:
arr_cal=arr*3-2
arr_cal

array([[ 1.6000001,  2.1999998,  2.8000002,  3.3999996],
       [ 4.8999996,  5.5      ,  6.1000004,  6.700001 ],
       [ 8.200001 ,  8.799999 ,  9.4      , 10.       ]], dtype=float32)

Question 6
Write code to show:
(a)	arr max value, and
(b)	arr mean value, and
(c)	arr standard deviation

In [7]:
max=arr.max()
mean=arr.mean()
std=arr.std()
print('arr max value is',max,',and')
print('arr mean value',mean,',and')
print('arr standard deviation value is',std)

arr max value is 4.0 ,and
arr mean value 2.6000001 ,and
arr standard deviation value is 0.92556286


Question 7
Access the shaded two value in arr, and output their multiplication value.  (1.6 and 3.4)
1.2	1.4	1.6	1.8
2.3	2.5	2.7	2.9
3.4	3.6	3.8	4.0

In [9]:
mult=arr[0,2]*arr[2,0]
print('their multiplication value is',mult)

their multiplication value is 5.44


Question 8
Write code to show the transpose of arr

In [10]:
t=arr.T
print('the transpose of arr is',t)

the transpose of arr is [[1.2 2.3 3.4]
 [1.4 2.5 3.6]
 [1.6 2.7 3.8]
 [1.8 2.9 4. ]]


Question 9
Write code to:
(a)	Reshape arr as (2,6) structure, and
(b)	Flatten arr and store the value in arr_flat

In [11]:
first=arr.reshape(2,6)
arr_flat=arr.reshape(-1)
print('The (2,6) structure is',first)
print('The value after flatten is',arr_flat)

The (2,6) structure is [[1.2 1.4 1.6 1.8 2.3 2.5]
 [2.7 2.9 3.4 3.6 3.8 4. ]]
The value after flatten is [1.2 1.4 1.6 1.8 2.3 2.5 2.7 2.9 3.4 3.6 3.8 4. ]


In [12]:
# Q1
print('Q1')
import numpy as np
arr=np.array([1.2,1.4,1.6,1.8,2.3,2.5,2.7,2.9,3.4,3.6,3.8,4.0],dtype='float32')
arr=arr.reshape(3,4)
print('the Numpy array named arr is\n',arr)
print() ; print('Q2')
# Q2
print("arr’s shape is\n",arr.shape,",and")
print("arr’s dtype is\n",arr.dtype)
print() ; print('Q3')
# Q3
arr_sqrt=np.sqrt(arr)   
print('the square root of the arr is\n',arr_sqrt)
print() ; print('Q4')
# Q4
arr2=arr > 2.7
print('the new Boolean array named arr2 is\n',arr2)
print() ; print('Q5')
# Q5
arr_cal=np.round(arr*3-2,3)
print('the array named arr_cal is\n',arr_cal)
print() ; print('Q6')
# Q6
max=arr.max()
mean=arr.mean()
std=arr.std()
print('arr max value is:\n',max,',')
print('arr mean value is:\n',mean,',and')
print('arr standard deviation value is:\n',std)
print() ; print('Q7')
# Q7
mult=arr[0,2]*arr[2,0]
print('the first number is: \n',arr[0,2],',and')
print('the another number is: \n',arr[2,0],',and')
print('their multiplication value is\n',mult)
print() ; print('Q8')
# Q8
t=arr.T
print('the transpose of arr is\n',t)
print() ; print('Q9')
# Q9
first=arr.reshape(2,6)
arr_flat=arr.reshape(-1)
print('The (2,6) structure is\n',first,',and')
print('The value after flatten is\n',arr_flat)

Q1
the Numpy array named arr is
 [[1.2 1.4 1.6 1.8]
 [2.3 2.5 2.7 2.9]
 [3.4 3.6 3.8 4. ]]

Q2
arr’s shape is
 (3, 4) ,and
arr’s dtype is
 float32

Q3
the square root of the arr is
 [[1.0954452 1.183216  1.264911  1.3416407]
 [1.5165751 1.5811388 1.6431677 1.7029387]
 [1.8439089 1.8973665 1.9493588 2.       ]]

Q4
the new Boolean array named arr2 is
 [[False False False False]
 [False False False  True]
 [ True  True  True  True]]

Q5
the array named arr_cal is
 [[ 1.6  2.2  2.8  3.4]
 [ 4.9  5.5  6.1  6.7]
 [ 8.2  8.8  9.4 10. ]]

Q6
arr max value is:
 4.0 ,
arr mean value is:
 2.6000001 ,and
arr standard deviation value is:
 0.92556286

Q7
the first number is: 
 1.6 ,and
the another number is: 
 3.4 ,and
their multiplication value is
 5.44

Q8
the transpose of arr is
 [[1.2 2.3 3.4]
 [1.4 2.5 3.6]
 [1.6 2.7 3.8]
 [1.8 2.9 4. ]]

Q9
The (2,6) structure is
 [[1.2 1.4 1.6 1.8 2.3 2.5]
 [2.7 2.9 3.4 3.6 3.8 4. ]] ,and
The value after flatten is
 [1.2 1.4 1.6 1.8 2.3 2.5 2.7 2.9 3.4 3.6 3